image: maven:3-jdk-11
cache:
  paths:
    - target/

stages:
  - build
  - deploy

.build-template: &build-template
  stage: build
  artifacts:
    paths:
      - target/biostudies.war
  script:
    - apt-get update
    - apt-get install firefox-esr -y
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
    - tar zxvf geckodriver-v0.26.0-linux64.tar.gz
    - mvn clean install spring-boot:repackage

.deploy-template: &deploy-template
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - cp "$ssh_key" ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - host0=`awk '{print $1}' <<< $host`
    - scp -oStrictHostKeyChecking=no ./target/biostudies.war "$user"@"$host0":"$deployDirectory"
    - scp "$application_properties" "$user"@"$host0":"$deployDirectory"/external.properties
    - >
      for host in $host; do
        ssh -oStrictHostKeyChecking=no "$user"@"$host" "$deployDirectory"/restart.sh
        echo "Waiting 220 seconds"
        sleep 220
      done

dev-build:
  <<: *build-template
  environment: dev
  only:
    - integration-test

dev:
  <<: *deploy-template
  environment: dev
  only:
    - develop

beta:
  <<: *deploy-template
  environment: beta
  only:
    - develop
  when: manual

master-build:
  <<: *build-template
  only:
    - master

prod-backup:
  <<: *deploy-template
  environment: prod-backup
  only:
    - master
  when: manual

prod:
  <<: *deploy-template
  environment: prod
  only:
    - master
  when: manual

preview:
  <<: *deploy-template
  environment: preview
  only:
    - master
  when: manual


