image: maven:3.3.9-jdk-8
cache:
  paths:
    - target/

stages:
  - build-war
  - deploy

maven-build:
  stage: build-war
  script:
    - sh ./tasks/makewar.sh ribs /ebi/teams/biostudies/frontend/
  only:
    - java12
  environment:
    name: ribs
    url: http://ribs.ebi.ac.uk:8080/biostudies/
  artifacts:
    paths:
      - target/biostudies.war


run-war:
  stage: deploy
  script:
    - sh ./tasks/runwar.sh ribs /ebi/teams/biostudies/frontend/
  only:
    - java12
  environment: ribs
