image: maven:latest
cache:
  paths:
    - target/

stages:
  - setup
  - build
  - deploy

setup:ribs:
  stage: setup
  script:
    - sh ./tasks/setup.sh
  environment: dev
  only:
    - java12

setup:test:
  stage: setup
  script:
    - sh ./tasks/setup.sh
  environment: test
  only:
    - develop

build:dev:
  stage: build
  script:
    - sh ./tasks/build.sh
  artifacts:
    paths:
      - target/biostudies.war

build:test:
  stage: build
  script:
    - sh ./tasks/build.sh
  artifacts:
    paths:
      - target/biostudies.war


deploy:dev:
  stage: deploy
  script:
    - sh ./tasks/deploy.sh
  environment: dev

deploy:test:
  stage: deploy
  script:
    - sh ./tasks/deploy.sh
  environment: test
  when: manual
