stages:
  - build
  # - deploy


maven-build:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - 'mvn clean install spring-boot:repackage'
  artifacts:
    paths:
      - target/



  #jdk-run-app:
  #  stage: deploy
  #  script:
  #    -java -D$(hostname -s))
