image: maven:3-jdk-11
cache:
  paths:
    - target/

stages:
  - build
  - deploy

.build-template: &build-template
  stage: build
  artifacts:
    paths:
      - target/biostudies.war
  script:
    - mvn -Dmaven.test.skip=true clean install spring-boot:repackage

.deploy-template: &deploy-template
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - cp "$ssh_key" ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - host0=`awk '{print $1}' <<< $host`
    - scp -oStrictHostKeyChecking=no ./target/biostudies.war "$user"@"$host0":"$deployDirectory"
    - cp "$application_properties" external.properties
    - echo -e "\ngit.commit.id.abbrev=$CI_COMMIT_SHORT_SHA" >> external.properties
    - scp external.properties "$user"@"$host0":"$deployDirectory"/external.properties
    - >
      for host in $host; do
        ssh -oStrictHostKeyChecking=no "$user"@"$host" "$deployDirectory"/restart.sh
        echo "Waiting 220 seconds"
        sleep 220
      done

dev-build:
  stage: build
  artifacts:
    paths:
      - target/biostudies.war
  script:
    - apt-get update
    - apt-get install libxss1 libappindicator1 libindicator7 -y
    - wget https://chromedriver.storage.googleapis.com/85.0.4183.83/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install ./google-chrome*.deb -y
    - mvn clean install spring-boot:repackage
  environment: dev
  only:
    - develop

dev:
  <<: *deploy-template
  environment: dev
  only:
    - develop

beta:
  <<: *deploy-template
  environment: beta
  only:
    - develop
  when: manual

master-build:
  <<: *build-template
  only:
    - master

prod-backup:
  <<: *deploy-template
  environment: prod-backup
  only:
    - master
  when: manual

prod:
  <<: *deploy-template
  environment: prod
  only:
    - master
  when: manual

preview:
  <<: *deploy-template
  environment: preview
  only:
    - master
  when: manual


