image: maven:latest
cache:
  paths:
    - target/

stages:
  - setup
  - build-and-deploy

.build-template: &build-and-deploy
  stage: build-and-deploy
  script:
    - sh ./tasks/setup.sh
    - sh ./tasks/build.sh
    - sh ./tasks/deploy.sh
  artifacts:
    paths:
      - target/biostudies.war

dev:
  <<: *build-and-deploy
  environment: dev
  only:
    - develop

test:
  <<: *build-and-deploy
  before_script:
    - cp "$test_properties" src/test/resources/test.properties
    - apt-get update
    - apt-get install -y build-essential chrpath libssl-dev libxft-dev libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev
    - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    - tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
    - export OPENSSL_CONF=/etc/ssl/
    - phantomjs-2.1.1-linux-x86_64/bin/phantomjs --version
  script:
    - sleep 120
    - mvn test -Dtest=IntegrationTestSuite -Dphantomjs.binary.path=phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  environment: test
  only:
    - develop


beta:
  <<: *build-and-deploy
  environment: beta
  only:
    - develop
  when: manual

