image: maven:latest
cache:
  paths:
    - target/

stages:
  - setup
  - build
  - deploy

.build-template: &build
  stage: build
  script:
    - sh ./tasks/setup.sh
    - sh ./tasks/build.sh
  artifacts:
    paths:
      - target/biostudies-$CI_ENVIRONMENT_SLUG.war

build:dev:
  <<: *build
  environment: dev
  only:
    - develop

build:test:
  <<: *build
  environment: test
  only:
    - develop

build:beta:
  <<: *build
  environment: beta
  only:
    - develop

.deploy-template: &deploy
  stage: deploy
  script:
    - sh ./tasks/deploy.sh $CI_ENVIRONMENT_SLUG

deploy:dev:
  <<: *deploy
  environment: dev
  only:
    - develop

deploy:test:
  <<: *deploy
  environment: test
  only:
    - develop
  when: manual

deploy:beta:
  <<: *deploy
  environment: beta
  only:
    - develop
  when: manual
