image: maven:3-jdk-11
cache:
  paths:
    - target/

stages:
  - build-and-deploy
  - integration-test

.build-template: &build-and-deploy
  stage: build-and-deploy
  artifacts:
    paths:
      - target/biostudies.war
  script:
    - sh ./tasks/setup.sh
    - sh ./tasks/build.sh
    - sh ./tasks/deploy.sh

dev:
  <<: *build-and-deploy
  environment: dev
  only:
    - develop

test:
  <<: *build-and-deploy
  before_script:
    - cp "$test_properties" src/test/resources/test.properties
    - apt-get update
    - apt-get install -y build-essential chrpath libssl-dev libxft-dev libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev
  environment: test
  only:
    - develop


beta:
  <<: *build-and-deploy
  environment: beta
  only:
    - develop
  when: manual


integration-test:
  stage: integration-test
  script:
    - echo 'integration test'
    - sleep 60
    - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    - tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
    - export OPENSSL_CONF=/etc/ssl/
    - mvn test -Dtest=IntegrationTestSuite -Dphantomjs.binary.path=/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  rules:
    - if: '$CI__ENVIRONMENT_SLUG == "test"'
    - when: always
    - when: never