image: maven:3-jdk-11
cache:
  paths:
    - target/

stages:
  - build
  - deploy

.build-template: &build-template
  stage: build
  artifacts:
    paths:
      - target/biostudies.war
  script:
    - mvn clean install spring-boot:repackage

.deploy-template: &deploy-template
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - cp "$ssh_key" ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - >
      for host in $host; do
        scp -oStrictHostKeyChecking=no ./target/biostudies.war "$user"@"$host":"$deployDirectory"
        scp "$application_properties" "$user"@"$host":"$deployDirectory"/external.properties
        ssh -oStrictHostKeyChecking=no "$user"@"$host" "$deployDirectory"/restart.sh
        echo "Waiting 120 seconds"
        sleep 120
      done

dev-build:
  <<: *build-template
  environment: dev
  only:
    - develop

dev:
  <<: *deploy-template
  environment: dev
  only:
    - develop

beta:
  <<: *deploy-template
  environment: beta
  only:
    - develop
  when: manual

master-build:
  <<: *build-template
  only:
    - master

prod-backup:
  <<: *deploy-template
  environment: prod-backup
  only:
    - master
  when: manual

prod:
  <<: *deploy-template
  environment: prod
  only:
    - master
  when: manual

