image: maven:latest
cache:
  paths:
    - target/

stages:
  - setup
  - build-and-deploy

.build-template: &build-and-deploy
  stage: build-and-deploy
  script:
    - sh ./tasks/setup.sh
    - sh ./tasks/build.sh
    - sh ./tasks/deploy.sh $CI_ENVIRONMENT_SLUG
  artifacts:
    paths:
      - target/biostudies-$CI_ENVIRONMENT_SLUG.war

dev:
  <<: *build-and-deploy
  environment: dev
  only:
    - develop

test:
  <<: *build-and-deploy
  environment: test
  only:
    - develop

beta:
  <<: *build-and-deploy
  environment: beta
  only:
    - develop
  when: manual

