image: maven:latest
cache:
  paths:
    - target/

stages:
  - setup
  - build
  - deploy

setup:ribs:
  stage: setup
  script:
    - sh ./tasks/setup.sh /nfs/ma/home/java/jdk-11.0.2/bin/java /ebi/teams/biostudies/frontend/
  environment: dev
  only:
    - java12


setup:test:
  stage: setup
  script:
    - sh ./tasks/setup.sh /nfs/ma/home/java/jdk-11.0.2/bin/java /ebi/teams/biostudies/frontend/
  environment: test
  only:
    - develop

    #- sh ./tasks/build.sh ribs ma-svc@ribs:/ebi/teams/biostudies/frontend/
    #- sh ./tasks/build.sh sixf tc_fg01@ves-ebi-6f:/nfs/www-prod/web_hx2/webadmin/tomcat/bases/fg/tc-fg-biostudies_test/deploy
    #- sh ./tasks/jdkset.sh /net/isilonP/public/rw/homes/tc_fg01/jdk-12.0.2/bin/java /nfs/www-prod/web_hx2/webadmin/tomcat/bases/fg/tc-fg-biostudies_test/deploy
    #- sh ./tasks/deploy.sh sixf ves-ebi-6f tc_fg01


build:
  stage: build
  script:
    - sh ./tasks/build.sh
  artifacts:
    paths:
      - target/biostudies.war

deploy:
  stage: deploy
  script:
    - sh ./tasks/deploy.sh
  when: manual
