image: maven:latest
cache:
  paths:
    - target/

stages:
  - setup
  - build
  - deploy

build:dev:
  stage: build
  script:
    - sh ./tasks/setup.sh
    - sh ./tasks/build.sh
  artifacts:
    paths:
      - target/biostudies.war
  environment: dev
  only:
    - develop

build:test:
  stage: build
  script:
    - sh ./tasks/setup.sh
    - sh ./tasks/build.sh
  artifacts:
    paths:
      - target/biostudies.war
  environment: test
  only:
    - develop

build:beta:
  stage: build
  script:
    - sh ./tasks/setup.sh
    - sh ./tasks/build.sh
  artifacts:
    paths:
      - target/biostudies.war
  environment: beta
  only:
    - develop


deploy:dev:
  stage: deploy
  script:
    - sh ./tasks/deploy.sh
  environment: dev
  only:
    - develop

deploy:test:
  stage: deploy
  script:
    - sh ./tasks/deploy.sh
  environment: test
  only:
    - develop
  when: manual

deploy:beta:
  stage: deploy
  script:
    - sh ./tasks/deploy.sh
  environment: beta
  only:
    - develop
  when: manual
